title: "nemo's blog"
email: "mail8@qq.com"
date_format: "ordinal"
description: "偶尔更新 nemo的笔记"
baseurl: ""
url: "http://www.missgao.net"
keywords: "missgao, nemo heng, nemo"
timezone: "Asia/Shanghai"
encoding: "utf-8"
side_bar_repo_limit: 5
author: "nemo.heng"

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:title/
gems:
    - jekyll-github-metadata
    - rouge
    # - jekyll-html-pipeline
    - jekyll-paginate 
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-toc
    # - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: missgao/missgao.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: missgao

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: duoshuo
# !!!Important!!!
# Please modify usernames below to yours
duoshuo_username: missgao
disqus_username: missgao
# lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: 

baidu:
    analytics_id: 5f98555052c4e3c64755c6406754d452